SELECT ROUTE, 
concat(round(SUM(D_BETWEEN_DIST),1),'km') AS TOTAL_DISTANCE, 
concat(round(AVG(D_BETWEEN_DIST),2),'km') AS AVERAGE_DISTANCE
FROM SUBWAY_DISTANCE AS s
GROUP BY s.ROUTE
ORDER BY SUM(D_BETWEEN_DIST) DESC;