SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM ITEM_INFO AS I
INNER JOIN ITEM_TREE AS T
ON I.ITEM_ID = T.ITEM_ID
WHERE T.PARENT_ITEM_ID IN(
    SELECT I.ITEM_ID AS ID
    FROM ITEM_INFO AS I
    WHERE I.RARITY = 'RARE'
    GROUP BY I.ITEM_ID)
ORDER BY I.ITEM_ID DESC;
    # AND T.PARENT_ITEM_ID IS NOT NULL;
# ORDER BY ITEM_ID DESC;
